"""AI-generated text detection endpoints.

Keeps the legacy ``/analyze`` endpoint (LLM prompt + local fallback) for
backward compatibility, and adds the deterministic multi-signal pipeline:

    POST /api/v1/ai-detection/text   – analyze pasted/provided text
    POST /api/v1/ai-detection/pdf    – analyze an uploaded PDF (with boxes)
    GET  /api/v1/ai-detection/{id}   – retrieve a stored analysis
    GET  /api/v1/ai-detection/{id}/file – original uploaded PDF bytes
    GET  /api/v1/ai-detection/{id}/highlighted – download the PDF with
                                                flagged regions highlighted
"""

import json
import logging
import os
import re
import uuid
from collections import Counter
from statistics import pstdev
from typing import List, Literal, Union

from fastapi import (
    APIRouter,
    Depends,
    File,
    HTTPException,
    UploadFile,
    status,
)
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, field_validator
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.ai_detector.detector_service import (
    analyze_pdf as run_pdf_detection,
)
from app.ai.ai_detector.detector_service import (
    analyze_text as run_text_detection,
)
from app.ai.ai_detector.schemas import (
    PdfDetectionResponse,
    TextDetectionResponse,
)
from app.core.auth import get_current_user_id
from app.core.config import settings
from app.core.quotas import QuotaContext, record_usage, require_ai_quota
from app.database.database import get_db
from app.models.subscription import UsageType
from app.services.llm_service import LLMService
from app.services.pdf_extraction_service import extract_pdf, PdfExtractionError
from app.services.pdf_highlight_service import build_highlighted_pdf

router = APIRouter()
llm_service = LLMService()
logger = logging.getLogger(__name__)

AI_DETECTION_STORAGE = os.path.join(settings.UPLOAD_DIR, "ai_detection")


class DetectionRequest(BaseModel):
    """Text submitted for AI-authorship analysis."""

    text: str = Field(
        ...,
        min_length=40,
        max_length=12000,
        description="The text to analyze; at least 40 characters are needed for a useful estimate.",
    )

    @field_validator("text", mode="before")
    @classmethod
    def normalize_text(cls, value: str) -> str:
        return value.strip() if isinstance(value, str) else value


class DetectionSignal(BaseModel):
    """A writing characteristic that influenced the estimate."""

    name: str = Field(..., min_length=1, max_length=80)
    explanation: str = Field(..., min_length=1, max_length=400)


class DetectionResponse(BaseModel):
    """AI-authorship estimate and transparent supporting signals."""

    score: int = Field(..., ge=0, le=100, description="Estimated AI-likelihood percentage")
    verdict: Literal["likely_human", "mixed_or_uncertain", "likely_ai"]
    confidence: int = Field(..., ge=0, le=100)
    summary: str = Field(..., min_length=1, max_length=500)
    signals: List[DetectionSignal] = Field(default_factory=list, max_length=5)
    disclaimer: str = (
        "This is an estimate, not proof of authorship. AI detectors can be wrong, "
        "especially for short, edited, or multilingual text."
    )


DETECTION_PROMPT = """You are a careful AI-authorship analysis assistant. Estimate whether the submitted passage was likely generated by an AI system.

Important principles:
- This is probabilistic classification, never proof. Do not claim certainty or identify a specific model.
- Consider formulaic phrasing, unusually uniform sentence structure, generic transitions, repetition, specificity, and natural variation together.
- Do not treat polished grammar, non-native English, academic style, or a few generic phrases as evidence by themselves.
- A score of 0 means likely human and 100 means likely AI. Use the full range thoughtfully.
- Use "mixed_or_uncertain" when signals conflict or the text is too short/edited to distinguish reliably.
- Return ONLY valid JSON matching this shape, with no markdown:
{"score": 0, "verdict": "likely_human", "confidence": 0, "summary": "", "signals": [{"name": "", "explanation": ""}]}
- Include 1 to 5 concise signals. Keep explanations grounded in the submitted text.

<text>
{text}
</text>"""


def _normalize_result(raw: str) -> DetectionResponse:
    """Extract and validate the model's JSON response."""
    try:
        payload = json.loads(LLMService._extract_json(raw))
        return DetectionResponse.model_validate(payload)
    except (json.JSONDecodeError, TypeError, ValueError) as exc:
        raise ValueError("The AI detector returned an invalid analysis") from exc


def _fallback_detection(text: str) -> DetectionResponse:
    """Return a transparent local estimate when the remote model is unavailable.

    This is deliberately conservative: it gives users useful feedback instead
    of failing, but keeps confidence low because stylometry is not proof of AI
    authorship and cannot replace the language-model analysis.
    """
    sentences = [part.strip() for part in re.split(r"[.!?]+", text) if part.strip()]
    words = re.findall(r"\b[\w']+\b", text.lower())
    sentence_lengths = [len(re.findall(r"\b[\w']+\b", sentence)) for sentence in sentences]
    unique_ratio = len(set(words)) / max(1, len(words))
    length_variation = pstdev(sentence_lengths) if len(sentence_lengths) > 1 else 0.0
    repeated_bigrams = Counter(zip(words, words[1:]))
    repeated_phrase_count = sum(count - 1 for count in repeated_bigrams.values() if count > 1)
    average_sentence_length = sum(sentence_lengths) / max(1, len(sentence_lengths))
    punctuation_count = len(re.findall(r"[,;:]", text))
    contraction_count = len(re.findall(r"\b\w+'\w+\b", text))
    transition_count = len(
        re.findall(
            r"\b(however|therefore|moreover|furthermore|additionally|in conclusion|thus|overall)\b",
            text.lower(),
        )
    )

    # Start from a neutral score, then combine independent, weak signals.
    # This intentionally avoids a fixed fallback percentage and keeps the
    # confidence low because stylometry cannot prove authorship.
    score = 48
    signals = []
    if len(sentence_lengths) >= 3 and length_variation < 3.0:
        score += 16
        signals.append(DetectionSignal(name="Uniform sentence rhythm", explanation="Sentence lengths are unusually consistent throughout the passage."))
    elif length_variation >= 5:
        score -= 16
        signals.append(DetectionSignal(name="Natural sentence variation", explanation="Sentence lengths vary noticeably, which is more consistent with natural drafting."))
    if unique_ratio < 0.45:
        score += 12
        signals.append(DetectionSignal(name="Repeated vocabulary", explanation="The passage reuses a relatively narrow set of words."))
    elif unique_ratio > 0.72:
        score -= 12
        signals.append(DetectionSignal(name="Specific vocabulary", explanation="The passage uses a broad vocabulary with relatively few repeated words."))
    if repeated_phrase_count >= 3:
        score += 10
        signals.append(DetectionSignal(name="Repeated phrasing", explanation="Some short word sequences recur across the passage."))
    if average_sentence_length > 28 and punctuation_count == 0:
        score += 7
        signals.append(DetectionSignal(name="Long formulaic sentences", explanation="The passage uses long sentences with little punctuation variation."))
    elif average_sentence_length < 12 or contraction_count > 0:
        score -= 7
        signals.append(DetectionSignal(name="Conversational variation", explanation="Shorter or contracted phrasing gives the passage a more conversational pattern."))
    if transition_count >= 2:
        score += 6
        signals.append(DetectionSignal(name="Formal transitions", explanation="Several formal transition phrases connect the ideas in a structured way."))

    # Add a small text-dependent tie breaker so two stylistically similar
    # passages do not always return the same rounded percentage.
    score += (sum(ord(char) for char in text[:120]) % 7) - 3

    score = max(0, min(100, score))
    verdict = "likely_ai" if score >= 65 else "likely_human" if score <= 35 else "mixed_or_uncertain"
    if not signals:
        signals.append(DetectionSignal(name="Limited stylistic evidence", explanation="The available writing patterns do not strongly favor either authorship category."))
    return DetectionResponse(
        score=score,
        verdict=verdict,
        confidence=min(55, 25 + len(sentences) * 3),
        summary="The language model was unavailable, so this is a low-confidence local writing-pattern estimate. Try again later for the full AI analysis.",
        signals=signals[:5],
    )


@router.post("/analyze", response_model=DetectionResponse)
async def analyze_text(
    request: DetectionRequest,
    db: AsyncSession = Depends(get_db),
    user_id: int = Depends(get_current_user_id),
    quota: QuotaContext = Depends(require_ai_quota(UsageType.AI_DETECTION)),
):
    """Estimate the likelihood that submitted text was AI-generated."""
    del quota  # The dependency enforces the plan quota; the context is not otherwise needed here.

    try:
        raw = await llm_service.generate(
            DETECTION_PROMPT.replace("{text}", request.text.strip()),
            temperature=0.1,
        )
        result = _normalize_result(raw)
    except Exception as exc:  # noqa: BLE001
        logger.warning("AI detection model unavailable; using local fallback: %s", exc)
        result = _fallback_detection(request.text)

    await record_usage(db, user_id, UsageType.AI_DETECTION)
    return result


# --------------------------------------------------------------------------
# Multi-signal detection endpoints
# --------------------------------------------------------------------------

class TextDetectionRequest(BaseModel):
    """Text submitted to the statistical multi-signal detector."""

    text: str = Field(
        ...,
        min_length=40,
        max_length=12000,
        description=(
            "The text to analyze. Short passages (below the minimum) return "
            "an insufficient_text message instead of a confident verdict."
        ),
    )

    @field_validator("text", mode="before")
    @classmethod
    def normalize_text(cls, value: str) -> str:
        return value.strip() if isinstance(value, str) else value


def _store_result(result_id: str, kind: str, payload: dict) -> None:
    """Persist a detection result so GET /{analysis_id} can replay it."""
    os.makedirs(AI_DETECTION_STORAGE, exist_ok=True)
    path = os.path.join(AI_DETECTION_STORAGE, f"{result_id}.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump({"kind": kind, "result": payload}, fh)


def _load_result(result_id: str):
    """Return stored {kind, result} or None.  result_id is sanitized so it
    can never escape the storage directory."""
    safe = re.sub(r"[^A-Za-z0-9_.-]", "", result_id or "")
    if not safe or safe != result_id:
        return None
    path = os.path.join(AI_DETECTION_STORAGE, f"{safe}.json")
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (json.JSONDecodeError, OSError):
        return None


@router.post("/text", response_model=TextDetectionResponse)
async def detect_text(
    request: TextDetectionRequest,
    db: AsyncSession = Depends(get_db),
    user_id: int = Depends(get_current_user_id),
    quota: QuotaContext = Depends(require_ai_quota(UsageType.AI_DETECTION)),
):
    """Analyze manually entered / pasted text with the multi-signal detector."""
    del quota

    result_id = f"txt-{uuid.uuid4().hex[:12]}"
    result = run_text_detection(request.text, result_id)
    _store_result(result_id, "text", result.model_dump())

    await record_usage(db, user_id, UsageType.AI_DETECTION)
    return result


@router.post("/pdf", response_model=PdfDetectionResponse)
async def detect_pdf_endpoint(
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
    user_id: int = Depends(get_current_user_id),
    quota: QuotaContext = Depends(require_ai_quota(UsageType.AI_DETECTION)),
):
    """Analyze an uploaded PDF, preserving page coordinates for highlights."""
    del quota

    original_name = file.filename or "document.pdf"
    if not original_name.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only PDF files are supported for PDF analysis.",
        )

    content = await file.read()
    if not content:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The uploaded file is empty.",
        )
    if len(content) > settings.MAX_UPLOAD_SIZE:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="The PDF exceeds the maximum allowed upload size.",
        )

    try:
        extraction = extract_pdf(content, original_name)
    except PdfExtractionError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc

    result_id = f"pdf-{uuid.uuid4().hex[:12]}"
    os.makedirs(AI_DETECTION_STORAGE, exist_ok=True)
    pdf_path = os.path.join(AI_DETECTION_STORAGE, f"{result_id}.pdf")
    with open(pdf_path, "wb") as fh:
        fh.write(content)

    pdf_url = f"/uploads/ai_detection/{result_id}.pdf"
    result = run_pdf_detection(
        pages=extraction.pages,
        file_name=original_name,
        pdf_url=pdf_url,
        result_id=result_id,
        scanned=extraction.scanned,
        extraction_warning=extraction.extraction_warning,
    )
    _store_result(result_id, "pdf", result.model_dump())

    await record_usage(db, user_id, UsageType.AI_DETECTION)
    return result


@router.get(
    "/{analysis_id}",
    response_model=Union[TextDetectionResponse, PdfDetectionResponse],
)
async def get_analysis(
    analysis_id: str,
    db: AsyncSession = Depends(get_db),
    user_id: int = Depends(get_current_user_id),
):
    """Retrieve a previously stored detection result by its id."""
    del db, user_id

    payload = _load_result(analysis_id)
    if payload is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Analysis not found.",
        )
    if payload.get("kind") == "pdf":
        return PdfDetectionResponse.model_validate(payload["result"])
    return TextDetectionResponse.model_validate(payload["result"])


@router.get("/{analysis_id}/file")
async def get_pdf_file(
    analysis_id: str,
    db: AsyncSession = Depends(get_db),
    user_id: int = Depends(get_current_user_id),
):
    """Stream the original uploaded PDF bytes (for in-page rendering)."""
    del db, user_id

    payload = _load_result(analysis_id)
    if payload is None or payload.get("kind") != "pdf":
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No PDF analysis found for this id.",
        )

    pdf_path = os.path.join(AI_DETECTION_STORAGE, f"{analysis_id}.pdf")
    if not os.path.isfile(pdf_path):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="The original PDF file is no longer available.",
        )

    file_name = payload.get("result", {}).get("file_name") or "document.pdf"
    safe_name = re.sub(r'[^A-Za-z0-9._-]', "_", file_name) or "document.pdf"

    return StreamingResponse(
        iter([open(pdf_path, "rb").read()]),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'inline; filename="{safe_name}"'
        },
    )


@router.get("/{analysis_id}/highlighted")
async def get_highlighted_pdf(
    analysis_id: str,
    db: AsyncSession = Depends(get_db),
    user_id: int = Depends(get_current_user_id),
):
    """Download the uploaded PDF with each flagged region highlighted."""
    del db, user_id

    payload = _load_result(analysis_id)
    if payload is None or payload.get("kind") != "pdf":
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No PDF analysis found for this id.",
        )
    result = payload.get("result", {})

    pdf_path = os.path.join(AI_DETECTION_STORAGE, f"{analysis_id}.pdf")
    if not os.path.isfile(pdf_path):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="The original PDF file is no longer available.",
        )

    with open(pdf_path, "rb") as fh:
        original = fh.read()

    try:
        highlighted = build_highlighted_pdf(
            original,
            result.get("pages", []),
            result.get("detections", []),
        )
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not render the highlighted PDF.",
        )

    file_name = result.get("file_name") or "document.pdf"
    base = file_name.rsplit(".", 1)[0] if "." in file_name else file_name
    safe_base = re.sub(r"[^A-Za-z0-9._-]", "_", base) or "document"

    return StreamingResponse(
        iter([highlighted]),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="highlighted-{safe_base}.pdf"'
        },
    )
