import DashboardLayout from "@/components/layout/DashboardLayout";
import apiClient from "@/lib/api";
import { useEffect, useState } from "react";
import { Quiz, Question } from "@/types";

export default function McqsPage() {
  const [quizzes, setQuizzes] = useState<Quiz[]>([]);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [newQuizTitle, setNewQuizTitle] = useState("");

  useEffect(() => {
    fetchQuizzes();
  }, []);

  const fetchQuizzes = async () => {
    try {
      const response = await apiClient.get("/api/v1/quizzes/");
      setQuizzes(response.data);
    } catch (error) {
      console.error("Failed to fetch quizzes:", error);
    }
  };

  const createQuiz = async () => {
    if (!newQuizTitle.trim()) return;
    try {
      await apiClient.post("/api/v1/quizzes/", {
        title: newQuizTitle,
        num_questions: 10,
      });
      setShowCreateModal(false);
      setNewQuizTitle("");
      fetchQuizzes();
    } catch (error) {
      console.error("Failed to create quiz:", error);
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">MCQ Practice</h1>
            <p className="text-gray-600 mt-1">Multiple choice questions generated by AI from your syllabus.</p>
          </div>
          <button
            onClick={() => setShowCreateModal(true)}
            className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700"
          >
            + New MCQ Set
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {quizzes.map((quiz) => (
            <div key={quiz.id} className="bg-white rounded-lg shadow p-6">
              <h3 className="font-bold text-lg text-gray-900">{quiz.title}</h3>
              <p className="text-gray-600 mt-2 text-sm">{quiz.description}</p>
              <div className="mt-4 flex items-center justify-between text-sm">
                <span className="text-gray-500">{quiz.questions?.length || 0} Questions</span>
                <button className="px-3 py-1 bg-primary-600 text-white rounded-md text-sm hover:bg-primary-700">
                  Start
                </button>
              </div>
            </div>
          ))}
        </div>

        {showCreateModal && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg p-6 w-96">
              <h2 className="text-xl font-bold mb-4">Create New MCQ Set</h2>
              <input
                type="text"
                value={newQuizTitle}
                onChange={(e) => setNewQuizTitle(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary-500"
                placeholder="Enter quiz title..."
              />
              <div className="flex justify-end space-x-3 mt-4">
                <button onClick={() => setShowCreateModal(false)} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-md">
                  Cancel
                </button>
                <button onClick={createQuiz} className="px-4 py-2 bg-primary-600 text-white rounded-md hover:bg-primary-700">
                  Create
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
