export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: "/dashboard",
  UPLOAD_SYLLABUS: "/upload-syllabus",
  STUDY_PLAN: "/study-plan",
  DAILY_QUIZ: "/daily-quiz",
  FLASHCARDS: "/flashcards",
  MCQ: "/mcqs",
  CODING_PRACTICE: "/coding-practice",
  AI_TUTOR: "/ai-tutor",
  PROGRESS: "/progress",
  WEAK_TOPICS: "/weak-topics",
  REVISION_PLAN: "/revision-plan",
  EXAM_SIMULATOR: "/exam-simulator",
  ANALYTICS: "/analytics",
  VOICE_LEARNING: "/voice-learning",
  PROFILE: "/profile",
  SETTINGS: "/settings",
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/v1/auth/login",
    REGISTER: "/api/v1/auth/register",
    REFRESH: "/api/v1/auth/refresh",
    LOGOUT: "/api/v1/auth/logout",
    ME: "/api/v1/auth/me",
  },
  SYLLABUS: "/api/v1/syllabus",
  STUDY_PLAN: "/api/v1/study-plan",
  FLASHCARDS: "/api/v1/flashcards",
  QUIZZES: "/api/v1/quizzes",
  CODING: "/api/v1/coding",
  TUTOR: "/api/v1/tutor",
  PROGRESS: "/api/v1/progress",
  ANALYTICS: "/api/v1/analytics",
  REVISION: "/api/v1/revision",
  WEAK_TOPICS: "/api/v1/weak-topics",
  VOICE: "/api/v1/voice",
  REPORTS: "/api/v1/reports",
  DASHBOARD: "/api/v1/dashboard",
};
